feat(web-iconics):  implement teams page
RealEskalate/Internship-2023 pull request #127
Opened 2023-05-04 06:05 UTC by zerihunMoges

![Screenshot 2023-05-03 230230](https://user-images.githubusercontent.com/91532718/236123785-1c023d32-2650-480c-91a5-a8bed1b2db09.png)

2023-05-04 08:20 UTC, sam5235 submitted a review, later dismissed

2023-05-04 08:57 UTC, sam5235 approved these changes

2023-05-09 13:52 UTC, ruthgdb requested changes
This looks nice overall. You need to address this comments before we can merge this.

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/TeamCard.tsx
When you define a component, make sure you use react.FC.

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/pages/teams/index.tsx
> +    <Teams></Teams>
If you're not going to add children you dont need closing tags, you can just use ```<Teams />```

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/pages/teams/index.tsx
>  function TeamsPage() {
Use react.FC here as well

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/Teams.tsx
This component can also be the index file on the teams folder. If you're just calling the other components here and nothing else, you dont need this component.

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/TeamsHero.tsx
>  function TeamsHero() {
Use react.FC here

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/TeamsHero.tsx
> +                    <Image src="/img/teams/team-work/team-work-1.png" alt="" width={322} height={316.7} className='contain absolute top-0 left-0 w-[35%]'/>
You can store this images in an array and loop over them. Most of these seem redundant.

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/Teams.tsx
> +                {teams.map((person, index) => <TeamCard key={index} name={person.name} description={person.description} job={person.job} avatar={person.avatar} socialMedia={person.socialMedia}></Team
You can just pass the whole team member object to the component. 

```
{teamMembers.map((teamMember, index) => <TeamCard key={index} teamMember={teamMember} /> )}
```

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/Teams.tsx
> +    const teams = teamMembers
What is the need for this

2023-05-09 13:52 UTC, ruthgdb commented on Web/starter_project_iconics/components/team/Teams.tsx
> +            <TeamsHero></TeamsHero>
You dont need a closing tag here as well

2023-05-11 07:27 UTC, ruthgdb requested changes
Looks good overall. Please address this reviews before we merge this.

2023-05-11 07:27 UTC, ruthgdb commented on Web/starter_project_iconics/components/teams/TeamMembersCard.tsx
[ver-nit] this is a single team member card so it shouldnt be plural. Change this file and the component inside it to `TeamMemberCard`

2023-05-11 07:27 UTC, ruthgdb commented on Web/starter_project_iconics/components/teams/TeamMembersCard.tsx
> +      <p className="text-center my-4 text-xl text-[#7D7D7D]">{teamMember.description}</p>
You can use the secondary color on your theme here

2023-05-11 07:27 UTC, ruthgdb commented on Web/starter_project_iconics/components/teams/TeamsHero.tsx
> +    const images: ImageProps[] = [{src: "/img/teams/team-work/team-work-1.png", alt:"", className:'contain absolute top-0 left-0 w-[35%]' ,width:322,height:316.7}, {src: "/img/teams/team-work/team-wo
This is not readable. Can you format this?

2023-05-12 12:45 UTC, ruthgdb approved these changes
Good job.

2023-05-12 12:46 UTC, merged