create an account information component
RealEskalate/Internship-2023 pull request #138
Opened 2023-05-04 09:09 UTC by kidus101

PR for account information page

2023-05-04 12:05 UTC, sam5235 commented on Web/starter_project_barbies/components/layout/Navbar.tsx
> +function Navbar({ activePage }: HeaderProps) {
give it type React.FC

2023-05-04 13:08 UTC, sam5235 requested changes
add type for the functional component

2023-05-09 06:15 UTC, Adona12 commented on Web/starter_project_barbies/pages/index.tsx
There's no change in this file so it's better not to track it

2023-05-09 06:17 UTC, Adona12 commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +                  <span className="sr-only">Facebook page</span>
You can use iteration on this part

2023-05-09 06:19 UTC, Adona12 requested changes
I've left comments

2023-05-16 11:49 UTC, ruthgdb requested changes
I've left some comments for you to address.

2023-05-16 11:49 UTC, ruthgdb commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +const Footer = () => {
Use react.FC here

2023-05-16 11:49 UTC, ruthgdb commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +
Use a loop instead of writing repetitive code

2023-05-16 11:49 UTC, ruthgdb commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +          <h3 className="text-lg font-bold text-stone-950  mb-4">Teams</h3>
Here as well

2023-05-22 11:30 UTC, nawrazi approved these changes, later dismissed

2023-05-22 11:37 UTC, ruthgdb submitted a review, later dismissed

2023-05-22 13:41 UTC, TsehaynehGetaneh approved these changes

2023-05-23 08:38 UTC, closed without merging