create a footer component for new branch
RealEskalate/Internship-2023 pull request #139
Opened 2023-05-04 11:10 UTC by kidus101

Pull request for latest pull request

2023-05-04 12:00 UTC, sam5235 commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +const Footer = () => {
add this for formality - React.FC

2023-05-04 12:00 UTC, sam5235 commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +                  <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 002
put this string somewhere on variable.

2023-05-04 12:03 UTC, sam5235 requested changes
fix the comments

2023-05-18 08:56 UTC, nawrazi commented on Web/starter_project_barbies/components/layout/Footer.tsx
> +      <div className="flex items-center">
Indentations seem off, I would suggest running lint.

2023-05-18 08:56 UTC, nawrazi requested changes
Looks good, I have left one comment.

2023-05-23 08:38 UTC, closed without merging