feat(web-vanguard): implement home page components
RealEskalate/Internship-2023 pull request #152
Opened 2023-05-08 08:37 UTC by Rediet-Ferew

This is the full implementation of home page of webs
![localhost_3001_(Nest Hub) (1)](https://user-images.githubusercontent.com/91590944/236776891-bf41de10-6b2f-4e06-b0e0-3ee58a0c838b.png)
Please review the implementations

2023-05-08 08:43 UTC, Segnicho commented on Web/starter_project_vanguard/components/home/BuildBetter.tsx
> +          <p className="text-center text-gray-700 md:text-lg">
for starter, format your code

2023-05-08 08:45 UTC, Segnicho commented on Web/starter_project_vanguard/components/home/HeroSection.tsx
> +        <div className="w-full ml-4 mt:11">
i'm not sure 'mt:11'  works

2023-05-08 08:49 UTC, Segnicho commented on Web/starter_project_vanguard/data/home/activities.json
> +[
this should be assigned some name and exported to be used. i am not sure how you are using this

2023-05-08 08:49 UTC, Segnicho commented on Web/starter_project_vanguard/data/home/success_rates.json
> +[
the same here

2023-05-08 08:51 UTC, Segnicho commented on Web/starter_project_vanguard/tailwind.config.js
> +        poppins: ['Poppins'],
this shouldn't be edited

2023-05-08 08:54 UTC, Segnicho commented on Web/starter_project_vanguard/components/home/BuildBetter.tsx
> +              xmlns="http://www.w3.org/2000/svg"
consider using react icons in place of svgs, I think it will make your code cleaner.

2023-05-08 12:16 UTC, Adona12 commented on Web/starter_project_vanguard/components/home/BuildBetter.tsx
> +const BuildBetter = () => {
Specify the type of the component.  You should use React.FC.

2023-05-08 12:16 UTC, Adona12 commented on Web/starter_project_vanguard/components/home/BuildBetter.tsx
> +        <div className="p-3 mt-10 ml-4 font-semibold text-white bg-blue-600 border-2 border-blue-500 rounded">
Is it really neccessary to define the color like this? Is it possible to use primary?

2023-05-08 12:19 UTC, Adona12 commented on Web/starter_project_vanguard/components/home/HelpUs.tsx
> +const HelpUs = () => {
You should define it using React.FC.

2023-05-08 12:21 UTC, Adona12 commented on Web/starter_project_vanguard/components/home/success-components/SuccessRate.tsx
Adding components on the folder name is not neccessary since it's already on the components folder

2023-05-08 12:22 UTC, Adona12 commented on Web/starter_project_vanguard/components/home/success-components/YearlySucess.tsx
[nit] There is a typo on the component name.

2023-05-08 12:24 UTC, Adona12 commented on Web/starter_project_vanguard/pages/index.tsx
[nit] remove the extra space between BuildBetter and SuccessRate

2023-05-08 12:25 UTC, Adona12 commented on Web/starter_project_vanguard/public/img/home-page/activity-1.jpg
The folder name should be consistent with the other. It's better if you name it as just "home"

2023-05-15 11:28 UTC, ruthgdb requested changes
Looks good overall. I've left some comments for you to address.

2023-05-15 11:59 UTC, Rediet-Ferew commented on Web/starter_project_vanguard/types/home/activity-model.ts
> +    left: boolean
yes it is, will do that

2023-05-19 11:47 UTC, Adona12 approved these changes
Reviewed

2023-05-19 12:15 UTC, merged