feat(web): implement blogs page
RealEskalate/Internship-2023 pull request #191
Opened 2023-05-10 21:02 UTC by TseganeshYifruBerta

![localhost_3000_blog (1)](https://github.com/RealEskalate/Internship-2023/assets/88632885/691d8d26-5d96-4d66-ad50-434b81cda3e7)

2023-05-11 11:53 UTC, Adona12 commented on Web/starter_project_vanguard/package.json
> +    "typeface-montserrat": "^1.1.13",
We don't need this. The fonts have been added already

2023-05-11 11:56 UTC, Adona12 commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +function BlogsCard(props: Props) {
I think this should be at the top

2023-05-11 11:57 UTC, Adona12 commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +interface Props {
The name should be descriptive

2023-05-11 11:58 UTC, Adona12 commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +function BlogsCard(props: Props) {
I think it's better to destructure the prop

2023-05-11 12:00 UTC, Adona12 commented on Web/starter_project_vanguard/components/blog/Search.tsx
> +const Button: React.FC<Props> = () => {
You can use the button component that has been created already

2023-05-11 12:03 UTC, Adona12 commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +const Tags: FC<MyTagProps> = ({ tags }) => {
Let's make it React.FC

2023-05-11 12:05 UTC, Adona12 requested changes
I've left comments

2023-05-12 07:37 UTC, ruthgdb requested changes
Looks good overall. I've left some comments for you to fix.

2023-05-12 07:37 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +interface MyTagProps {
Can we move this to a separate component in  `components/common` folder

2023-05-12 07:37 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +          <Link href={`./single-blog?id=${encodedId}`} passHref>
Theres a better way of doing this by using dynamic routes. Refer to [this](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes) doc on how to do it this way.

2023-05-12 11:38 UTC, ruthgdb requested changes
Make sure you address all the comments here before re-requesting :)

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/tag.tsx
Lets stick to PascalCase for component names

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +          <Link href={`./single-blog?id=${encodedId}`} passHref>
You can remove this route for now and you can fix it in another PR. Make sure to leave a comment to indicate that.

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/blog/index.tsx
> +          {currentBlogs.map((blog: Blog) => (
[nit] if the array is `currentBlogs` then the single blog should be `currentBlogs`

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/blog/index.tsx
> +      <div className="h-44 ">
[very-nit] remove the space after h-44

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/tag.tsx
If this component if for all the tags, then it should be named `Tags.tsx`. Using just `Tag` implies that this component only returns a single Tag.

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/tag.tsx
> +            <span className="text-lg font-semibold  text-gray-500">{tag}</span>
[very-nit] remove the space after font-semibold

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +      <div className="flex border-t-2  w-3/4 border-gray-300 pl-10">
[very-nit] remove the space after border-t-2

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +        <div className=" items-start w-3/5 pt-4 pb-4 pr-0">
[very-nit] remove the space at the beginning

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +                  className={`rounded-full object-cover `}
[very-nit] remove the space after object-cover

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +                <span className="text-2xl font-bold ">{title}</span>
[very-nit] remove the space after font-bold

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +                <span className="text-gray-500 font-light text-lg ">
[very-nit] remove the space after lg

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +        <div className="flex justify-center items-center w-1/4 pl-0 ">
[very-nit] remove the space after pl-0

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/blog/BlogsCard.tsx
> +    <div className=" flex flex-wrap justify-center w-6/5 ">
[very-nit] remove the space at the beginning

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/Search.tsx
Make sure this component contains objects related to search only.

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/Search.tsx
And since its in the common folder, it can be used by other components or pages so I suggest you remove all content related to blogs or other specific content.

2023-05-12 11:38 UTC, ruthgdb commented on Web/starter_project_vanguard/components/common/Search.tsx
> +      <div className=" flex flex-wrap justify-center h-20 ">
[very-nit] remove the space at the start and end

2023-05-15 06:16 UTC, ruthgdb approved these changes
Good job.

2023-05-15 06:29 UTC, merged