feat(web-barbies): migrate blog data to json-server
RealEskalate/Internship-2023 pull request #197
Opened 2023-05-11 11:07 UTC by nawrazi

2023-05-11 12:21 UTC, Adona12 commented on Web/starter_project_barbies/pages/api/blogs/index.ts
> +}
We already have this on the type folder

2023-05-11 12:29 UTC, Adona12 commented on Web/starter_project_barbies/pages/blogs/[id].tsx
> +    let blog = result.data
How about destructuring this?

2023-05-12 07:36 UTC, YiseBoge commented
i would have loved descriptions on this pr about what it does and what the assumptions are (it is especially important when working on the more complicated code bits)

2023-05-12 08:21 UTC, nawrazi commented
> i would have loved descriptions on this pr about what it does and what the assumptions are (it is especially important when working on the more complicated code bits)
Done

2023-05-12 09:08 UTC, YiseBoge requested changes
looks nice but i have left some changes to make

2023-05-12 09:08 UTC, YiseBoge commented on Web/starter_project_barbies/pages/api/blogs/[id].ts
if you are indeed using a json server api, i believe you should define the base url as an env vairable and just load it from rtk query

Is there anything that would prevent that?

2023-05-12 09:08 UTC, YiseBoge requested changes
looks nice but i have left some changes to make

2023-05-12 09:47 UTC, nawrazi commented on Web/starter_project_barbies/types/blog.ts
> +    relatedBlogs: string[];
Yes, a list of string ID's.

2023-05-12 18:21 UTC, nawrazi commented
@YiseBoge I have addressed all comments, please re-review.

2023-05-18 09:06 UTC, kkstarkk requested changes
looks good overall and i have left some minor comments

2023-05-18 09:06 UTC, kkstarkk commented on Web/starter_project_barbies/pages/blogs/index.tsx
> +  const blogsResult = useGetBlogsQuery()
again use object destructuring

2023-05-18 11:02 UTC, kkstarkk approved these changes

2023-05-18 12:13 UTC, ruthgdb approved these changes

2023-05-18 12:21 UTC, merged