Jebessa.update blog card
RealEskalate/Internship-2023 pull request #212
Opened 2023-05-12 11:06 UTC by jebessaD

![image](https://github.com/RealEskalate/Internship-2023/assets/89038777/6dd35ab7-8e80-4844-98f9-e08e154060ce)

> To the blog card, add a delete and update button. The buttons are only visible for blogs created by the user (only for the myblog component).
> Update Json file: change _id to id

2023-05-18 11:54 UTC, Endalebob requested changes

2023-05-18 11:54 UTC, Endalebob commented on Web/starter_project_vanguard/components/blog/BlogCard.tsx
-The numberFormater function could benefit from better naming (e.g., numberFormatter) for consistency and clarity.

- The usage of the max-w-sm and relative classes in the wrapping div seems unnecessary since these classes are not utilized further. Consider removing them if they don't serve any purpose.

2023-05-18 11:54 UTC, Endalebob commented on Web/starter_project_vanguard/components/profile/MyBlogs.tsx
* The handleDelete function is currently implemented as a no-op ((id) => {null}). Make sure to replace it with the actual logic for deleting a blog.

* Consider adding a key to the mapped BlogCard components using a unique identifier from the blog object instead of using the index. This ensures better rendering and avoids any potential issues when the order of items changes.

2023-05-19 12:26 UTC, bisrat-walle requested changes

2023-05-19 12:26 UTC, bisrat-walle commented on Web/starter_project_vanguard/components/blog/BlogCard.tsx
>  import { Blog } from '../../types/blog/blog'
like import { Blog } from '@/types/blog/blog'

2023-05-21 09:34 UTC, zelalemyetsedaw commented on Web/starter_project_vanguard/components/blog/BlogCard.tsx
it is better to add our team name when you create a PR

2023-05-22 07:52 UTC, bisrat-walle approved these changes

2023-05-22 07:57 UTC, Endalebob approved these changes

2023-05-22 07:59 UTC, ruthgdb submitted a review, later dismissed

2023-05-22 08:25 UTC, ruthgdb approved these changes

2023-05-22 08:26 UTC, merged