feat(iconics): fetch blog api
RealEskalate/Internship-2023 pull request #215
Opened 2023-05-12 12:21 UTC by Aklile-Yilma

2023-05-18 08:24 UTC, Henok-Matheas commented
You haven't provided a reference image for the task you worked on

2023-05-18 08:29 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
Use the common backend_url for the base url.

2023-05-18 08:30 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
change the reducer path to make it more descriptive, in this case the reducerPath should be something like "blog"

2023-05-18 08:37 UTC, zerihunMoges commented on Web/starter_project_iconics/pages/blog/index.tsx
> +  console.log(blogsData)
it's important to ensure that any debugging statements, including console.log, are removed before committing the code.

2023-05-18 08:59 UTC, Henok-Matheas requested changes
change these things before merging.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/_app.tsx
the store name should be a global one, you are wrapping the whole app using the blogApi store.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
change the reducer path to make it more descriptive, in this case the reducerPath should be something like "blog"

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
Use the common backend_url for the base url set up in the config folder.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
you can change the isLoading part to be more of a skeleton.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
the Blogs component should have it's type defined like React.FC or something.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
some of the spacing is inconsistent, so use prettier to format it, you can use the extension if you want.

2023-05-18 08:59 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
you aren't handling the case where the API returns an error.

2023-05-18 10:31 UTC, Henok-Matheas requested changes
Please address these issues prior to merging.

2023-05-18 10:31 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
some of the spacing is inconsistent, so use prettier to format it, you can use the extension if you want.

2023-05-18 10:31 UTC, Henok-Matheas commented on Web/starter_project_iconics/pages/blog/index.tsx
> +const Blogs = () => {
the Blogs component should have it's type defined like React.FC or something.

2023-05-18 10:31 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
> +  baseQuery: fetchBaseQuery({ baseUrl: API_BASE_URL }),
Use the common backend_url for the base url set up in the config folder.

2023-05-18 10:31 UTC, Henok-Matheas commented on Web/starter_project_iconics/store/features/api/blog-api.ts
> +      query: () => 'blogs',
change the reducer path to make it more descriptive, in this case the reducerPath should be something like "blog"

2023-05-22 08:05 UTC, zerihunMoges submitted a review, later dismissed

2023-05-22 11:32 UTC, Henok-Matheas approved these changes
LGTM.

2023-05-22 11:54 UTC, ruthgdb approved these changes

2023-05-22 11:55 UTC, merged