feat(Web-vanguard): implement Single Blog
RealEskalate/Internship-2023 pull request #225
Opened 2023-05-15 11:23 UTC by zelalemyetsedaw

In this branch i implement the single-blog page UI
The mobile view is
![localhost_3000_blog_644b788907d74878251cfc02(iPhone SE)](https://github.com/RealEskalate/Internship-2023/assets/96313277/ced42e6a-04ad-4fda-ab43-a8f7699542ec)

The output on desktop is 
![localhost_3000_blog_644b788907d74878251cfc02(Nest Hub Max) (1)](https://github.com/RealEskalate/Internship-2023/assets/96313277/67be2c70-6bc7-4701-a5d4-b9af1a756cf7)

2023-05-18 06:42 UTC, nawrazi commented on Web/starter_project_vanguard/components/blog/RelatedBlog.tsx
> +const Related = (props:Props) => {
Can you rename this component to something a bit more descriptive?

2023-05-18 06:48 UTC, nawrazi commented on Web/starter_project_vanguard/pages/blog/[id].tsx
> +          PROGRAMMING, TECH | {blog.time} MIN READ
I think the blog tags should also come from the blog object itself, rather than hardcoded like this.

2023-05-18 06:52 UTC, nawrazi commented on Web/starter_project_vanguard/pages/blog/[id].tsx
> +            <br /> {blog.description}
This isn't the best way to do this, you should expect blog.description to be one large block of text, and then you can separate it into multiple paragraphs by splitting using the newline character (\n).

2023-05-18 06:53 UTC, nawrazi requested changes
Looks good overall, I have left some comments though.

2023-05-20 08:21 UTC, nawrazi approved these changes

2023-05-20 08:56 UTC, Adona12 approved these changes
Reviewed

2023-05-20 08:58 UTC, merged