Zerihun.button (team iconics)
RealEskalate/Internship-2023 pull request #23
Opened 2023-04-22 16:32 UTC by zerihunMoges

create a button component

2023-04-22 20:57 UTC, YiseBoge commented
please rename the PR name to follow conventional commits (because that is what will be used when using squash and merge by default)

2023-04-23 17:52 UTC, zerihunMoges commented
> please rename the PR name to follow conventional commits (because that is what will be used when using squash and merge by default)
> 
> And please put in screenshots and description of what you have implemented in the description

![button](https://user-images.githubusercontent.com/91532718/233856306-ceb7e56f-08fa-42f0-8fac-171600b4009f.png)

I created a generic button component that can be modified and also accepts optional icon props if needed

2023-04-24 10:22 UTC, Adona12 requested changes
The branch is out of date so make sure to rebase

2023-04-24 10:47 UTC, zerihunMoges commented
> The branch is out of date so make sure to rebase

done

2023-04-26 11:26 UTC, zerihunMoges commented
> The branch is out of date so make sure to rebase

![Screenshot 2023-04-26 041350](https://user-images.githubusercontent.com/91532718/234561158-b708716c-e958-406d-bf86-1e3b18f1dc49.png)

2023-04-26 11:42 UTC, Adona12 commented on Web/starter_project_iconics/components/common/Button.tsx
> +    <button {...props} className={clsx( outline? 'outline outline-2 outline-primary text-primary bg-white hover:bg-primary hover:text-white' : 'text-white bg-primary hover:bg-blue-600', 'flex justify
We don't need to have the hover propery

2023-04-26 12:51 UTC, Adona12 approved these changes
LGTM

2023-04-26 12:52 UTC, merged