feat(web-barbies) : Add new blog post
RealEskalate/Internship-2023 pull request #230
Opened 2023-05-15 12:23 UTC by TsehaynehGetaneh

# Add new blog post
  - blog post for a user is implemented using RTK Query and local json-server.
  
  please, review the implementation.

<img width="953" alt="newBlog-desktop" src="https://github.com/RealEskalate/Internship-2023/assets/93071822/642b2985-bcd7-4859-a729-579ebf635b7a">

2023-05-18 11:18 UTC, hello-world-was-taken requested changes
Good job overall, one more thing, let's make sure we are running prettier before creating PRs.

2023-05-18 11:18 UTC, hello-world-was-taken commented on Web/starter_project_barbies/components/blog/BlogForm.tsx
> +    <label htmlFor={identity} className="bg-white text-gray rounded-md px-4 py-2 hover:bg-gray-200">
we should stick with the convention we are using for the other ids

2023-05-18 11:18 UTC, hello-world-was-taken commented on Web/starter_project_barbies/components/blog/BlogForm.tsx
> +              <FileInput text="Upload File" identity="upload-file" />
[nit] again lets change them to ids

2023-05-18 12:17 UTC, hello-world-was-taken approved these changes

2023-05-19 11:38 UTC, Adona12 approved these changes
Reviewed

2023-05-19 11:39 UTC, merged