add(mobile-matador): Implement Homepage Appbarr
RealEskalate/Internship-2023 pull request #44
Opened 2023-04-24 10:05 UTC by duressaJemal

Implement homepage appbarr UI that contains navigation menu button, title, and profile avatar with necessary styling applied. 
![home_page_app_barr](https://user-images.githubusercontent.com/88533649/233965219-10815061-82a8-418c-b4e2-9cf2ca6299c9.png)

2023-04-24 10:33 UTC, BekyH requested changes
Don't Modify the example folder. It is a placeholder to show the structure. So create your own folder inside the features directory with feature_name and make it a similar structure to the example folder. Migrate all the changes made in the example folder.

2023-04-25 11:26 UTC, lealemgetahun commented on Mobile/starter_project_matador/lib/features/home_page/presentation/widgets/appbar_title.dart
> +        style: GoogleFonts.poppins(
Don't use google fonts use asset for font

2023-04-26 07:40 UTC, lealemgetahun approved these changes

2023-04-26 07:41 UTC, lealemgetahun approved these changes

2023-04-26 07:53 UTC, BekyH submitted a review, later dismissed

2023-04-26 09:08 UTC, lealemgetahun approved these changes

2023-04-26 11:51 UTC, lealemgetahun submitted a review, later dismissed

2023-04-26 12:12 UTC, Adona12 approved these changes
LGTM

2023-04-26 12:16 UTC, Redi22 requested changes

2023-04-26 12:33 UTC, Redi22 approved these changes
LGTM

2023-04-26 12:46 UTC, YiseBoge approved these changes
let's avoid committing everything in the future

2023-04-26 12:49 UTC, merged