feat(web-iconics) : implement add blog page
RealEskalate/Internship-2023 pull request #46
Opened 2023-04-24 13:52 UTC by Mekdeskebede

In this branch add blog page is implemented
![Screenshot 2023-04-24 164635](https://user-images.githubusercontent.com/91591156/234016750-f3de53d9-9e6f-45db-8a7a-74b51fc9bba6.png)
![Screenshot 2023-04-24 164735](https://user-images.githubusercontent.com/91591156/234016855-374d7219-1a66-4ef9-8b59-c7a3171b8b0c.png)

2023-04-24 19:56 UTC, Aklile-Yilma commented
LGTM

2023-04-24 19:57 UTC, Aklile-Yilma submitted a review, later dismissed
LGTM

2023-04-24 19:57 UTC, Aklile-Yilma commented on Web/starter_project_iconics/package.json
> +    "react-quill": "^2.0.0",
It's great that you built a functional UI, with WYSIWYG editor.

2023-05-03 08:42 UTC, sam5235 submitted a review, later dismissed

2023-05-03 08:48 UTC, sam5235 submitted a review, later dismissed

2023-05-04 13:05 UTC, sam5235 requested changes
if you get stuck on the vercel error,create new branch(your branch is outdated), build, and rebase your branch.

2023-05-09 10:38 UTC, merged