Bisrat | about page
RealEskalate/Internship-2023 pull request #47
Opened 2023-04-24 17:07 UTC by bisrat-walle

![image](https://user-images.githubusercontent.com/87634885/234066393-db4d4ca5-ba3a-4e30-b6bd-d6f647398d3e.png)
![image](https://user-images.githubusercontent.com/87634885/234066495-7ef84be2-92b3-453e-8d56-c26206559d9c.png)
![image](https://user-images.githubusercontent.com/87634885/234066586-9e514ce2-6e1c-4b85-87aa-ff23864de0ec.png)
![image](https://user-images.githubusercontent.com/87634885/234066699-2fbc56ba-1031-4357-9d8a-87fd91f1921f.png)
![image](https://user-images.githubusercontent.com/87634885/234066765-62c8c548-9c1a-4ddd-962e-7083aaaa63cf.png)

2023-04-24 19:15 UTC, ruthgdb requested changes

2023-04-24 19:15 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/about/index.tsx
> +            <span className="font-lato text-[#2B2A35]">The Problem We </span>{' '}
[nit] Is there a reason you're trying to change the font for this span only?

2023-04-25 08:06 UTC, ruthgdb requested changes

2023-04-25 08:06 UTC, ruthgdb commented on Web/starter_project_vanguard/tailwind.config.js
> +        aboutbackground: '#FDFEFF',
[nit] the background color for most the pages is the same so can you give it a more inclusive name?

2023-04-25 08:06 UTC, ruthgdb commented on Web/starter_project_vanguard/tailwind.config.js
> +        'aboutnormal-text': '#2B2A35',
[nit] can you find a better name for this as well?

2023-05-03 11:37 UTC, sam5235 commented on Web/starter_project_vanguard/components/about/A2SVSession.tsx
> +function A2SVSession({ image, title, content }: any) {
why the type is any, you can make it string.

2023-05-03 11:39 UTC, sam5235 commented on Web/starter_project_vanguard/components/about/Activities.tsx
> +function Activities({ studentGrowthRate, learningRate, growthRate }: any) {
remove all "any" types

2023-05-03 11:51 UTC, sam5235 commented on Web/starter_project_vanguard/components/about/CenteredImage.tsx
> +      <Image src={image} alt={''}></Image>
put something in the alt, this comment is for all images too

2023-05-03 11:51 UTC, sam5235 commented on Web/starter_project_vanguard/pages/about/index.tsx
> +        {socialProjects.map((project) => {
every child should have key....this might cause vercel error.

2023-05-04 11:53 UTC, sam5235 approved these changes

2023-05-08 08:04 UTC, ruthgdb commented on Web/starter_project_vanguard/public/img/aboutus/icons/africa-icon.svg
Can you rename the folder "aboutus" to "about" to make it more consistent

2023-05-08 08:05 UTC, ruthgdb commented on Web/starter_project_vanguard/components/about/A2SVSession.tsx
> +function A2SVSession({ image, title, content }: SessionComponentProp) {
Can you also add recat.FC to all your component files as well

2023-05-08 08:55 UTC, ruthgdb approved these changes
LGTM. Good job.

2023-05-08 10:55 UTC, merged