Implement Write article page
RealEskalate/Internship-2023 pull request #48
Opened 2023-04-24 18:11 UTC by MuleHakim

2023-04-24 22:50 UTC, MuleHakim commented
![esk](https://user-images.githubusercontent.com/91600753/234132846-5650ed9c-01b9-40d4-8cf2-31bf36a1a385.png)

2023-04-25 07:53 UTC, lealemgetahun reviewed
Modularize your code

2023-04-25 09:00 UTC, MuleHakim commented
I implemented the Write Article page responsive and modular by dividing it into smaller, reusable widgets like ArticleTitle, TitleWidget, SubtitleWidget, TagsWidget, AddManyTags, ContentWidget, and PublishButton. This makes the code more organized, maintainable, and easier to test and debug.

2023-04-25 11:51 UTC, Redi22 requested changes
Please address the comments given and make the components. Make sure each component you created is being used if not make sure you remove it.

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/add_many_tags.dart
One text is not component enough to be one custom widget by itself. Please remove this widget as it is not even a dynamic one.

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/article_title.dart
Same goes for this one

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/content_widget.dart
> +class ContentWidget extends StatelessWidget {
You should rename this to something like ContentFormField

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/subtitle_widget.dart
This is too small of a component again. I would advise in making two re-usable widgets one for normal text form fields and another for text area form fields. You can create these two and re-use their styles to create all the fields in the UI.

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/tags_widget.dart
> +class TagsWidget extends StatelessWidget {
Rename to TagSelectorField or any other better name

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/title_widget.dart
Same goes here...it is not component enough to be a widget

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/example/presentation/screen/write_article_screen.dart
> +class WriteArticlePage extends StatelessWidget {
I would rename this to ArticleFormPage because it will also be used to edit articles.

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/example/presentation/screen/write_article_screen.dart
> +        title: const Text(
You didn't even use the widget "ArticleTitle" here so removing the widget would be nice like I said above

2023-04-25 11:51 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/widgets/title_widget.dart
This file is as big as it was on the original review. The components are created but not used here. Some components are useless to be that small so I have commented on them. Remove those and use the rest of the components here to make the file size smaller as well.

2023-04-26 12:29 UTC, MuleHakim commented on Mobile/starter_project_matador/lib/core/shared_widgets/article_button.dart
File renamed to article

2023-05-02 07:20 UTC, Redi22 requested changes

2023-05-02 07:20 UTC, Redi22 commented on Mobile/starter_project_matador/lib/features/article/presentation/screen/write_article_screen.dart
rename to write_article_page

2023-05-02 07:56 UTC, Redi22 approved these changes
LGTM

2023-05-02 11:38 UTC, merged