implement success stories page
RealEskalate/Internship-2023 pull request #50
Opened 2023-04-24 18:44 UTC by FevenBelay23

![story](https://user-images.githubusercontent.com/91492132/234087406-4bc53ec0-4236-4636-901b-411dec33d788.png)

2023-04-25 07:03 UTC, Adona12 commented on Web/starter_project_iconics/public/success-stories-images/Google.png
Let's stick to kebab case for everything other than components

2023-04-25 07:08 UTC, Adona12 commented on package.json
Why did you have to add tailwindcss as a devdependecy? It's already been added.

2023-04-25 07:16 UTC, Adona12 commented on Web/starter_project_iconics/public/success-stories-images/InstDeep.png
It would be great if you add the `/success-stories-images` subfolder in  `/img` subfolder to indicate that the contents are images. You could also further divide the images into subfolders, for example, by creating separate subfolders for `/people` and `/companies` to make it clearer.

2023-04-25 07:17 UTC, Adona12 commented on Web/starter_project_iconics/public/success-stories-images/yishak.png
This is not how you write Yisehak

2023-04-25 07:19 UTC, Adona12 commented on Web/starter_project_iconics/pages/story/success-stories.tsx
> +          <GlassImage
Instead of writing the data statically, you can have a json file and import it here. You should also loop throught the data.

2023-04-25 07:22 UTC, Adona12 commented on Web/starter_project_iconics/components/story/GlassImage.tsx
> +          <p className="px-4 pb-4 font-poppins text-xl text-gray-50">{location}</p>
The text color can also be configured globally so others can resuse it.

2023-04-25 07:24 UTC, Adona12 requested changes
I've left some comments

2023-05-02 11:00 UTC, sam5235 commented on Web/starter_project_iconics/components/story/PartnersLogos.tsx
> +const partnerSection = [
put this on the data section using JSON file, if another partners came along you don't have to touch the code here.

2023-05-02 11:04 UTC, sam5235 approved these changes

2023-05-03 07:57 UTC, Adona12 approved these changes
LG

2023-05-03 08:07 UTC, merged