feat(web-iconics): create blog card and one profile page
RealEskalate/Internship-2023 pull request #59
Opened 2023-04-25 08:05 UTC by blenassefa2

In this branch a new common component is created called Blog card  and additionally one profile page is also created
I've addressed all the suggestions and reviews in the previous branch
the two figma cards and the page look as follows:
![image](https://user-images.githubusercontent.com/62964622/234213648-ca4b4051-ceb8-4801-9094-117b0dab07df.png)
![image](https://user-images.githubusercontent.com/62964622/234213659-2d5b3d38-75ff-4849-9e31-cf822f29b23c.png)
![image](https://user-images.githubusercontent.com/62964622/234213899-f5283ffe-d3a1-4e7e-86a1-8ce66ed89609.png)

The created blog card looks as follows:
![image](https://user-images.githubusercontent.com/62964622/234213042-0a2711f5-9553-49c8-a633-10f6e9bf7c96.png)

The created page looks as follows:
![image](https://user-images.githubusercontent.com/62964622/234213206-3fe101b8-e8d7-4c7d-b734-57717ec8e9fd.png)

2023-04-25 19:19 UTC, Aklile-Yilma submitted a review, later dismissed
Looks good to me

2023-04-25 19:19 UTC, Aklile-Yilma commented on Web/starter_project_iconics/types/blog.tsx
> +import { User } from './user'
Folder path could be type/profile/blog

2023-04-25 19:19 UTC, Aklile-Yilma commented on Web/starter_project_iconics/data/blogs.ts
> +
Also it's preferred to make it a json file

2023-04-25 19:19 UTC, Aklile-Yilma commented on Web/starter_project_iconics/components/profile/profileLayout.tsx
> +const ProfileLayout: React.FC<ProfileProps> = ({
Great that you created a layout 👍

2023-04-25 19:19 UTC, Aklile-Yilma commented on Web/starter_project_iconics/components/common/blogCard.tsx
> +}
Is there a way to make this page smaller, too many lines. Maybe you could import some of the jsx you return based on the condition

2023-05-02 08:56 UTC, sam5235 commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +const BlogCard: React.FC<Props> = ({ card, feature }) => {
you didn't give the type for the props here.

2023-05-02 09:01 UTC, sam5235 approved these changes

2023-05-02 10:39 UTC, sam5235 submitted a review, later dismissed

2023-05-04 11:50 UTC, ruthgdb requested changes
Looks good overall. I've left some comments for you to address before we can merge this.

2023-05-04 11:50 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCardFooter.tsx
> +interface Props {
Can you give it a more descriptive name like [componentName]Props

2023-05-04 11:50 UTC, ruthgdb commented on Web/starter_project_iconics/components/profile/myBlogs.tsx
> +type MyblogsProps = {
lets stick to PascalCase naming here

2023-05-04 11:50 UTC, ruthgdb commented on Web/starter_project_iconics/components/profile/profileLayout.tsx
> +          className={`text-lg font-semibold  text-gray-700 pl-0 pr-4 pt-2 pb-5 hover:text-primary ${
Can you use the colors already defined in your tailwind.config file? If its not define you can add it too since you've used it other places

2023-05-04 11:50 UTC, ruthgdb commented on Web/starter_project_iconics/components/profile/profileLayout.tsx
> +          className={`text-lg font-semibold  text-gray-700 px-4 pt-2 pb-5 hover:text-primary ${
Here as well

2023-05-09 11:09 UTC, Adona12 commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +}
The name is vagues, let's be more clear

2023-05-11 05:21 UTC, blenassefa2 commented
> Looks good overall. I've left some comments for you to address before we can merge this.

I've addressed the comments and re requested a review

2023-05-12 06:01 UTC, ruthgdb commented on Web/starter_project_iconics/components/profile/MyBlogsPage.tsx
I suggest you find a better file name for this (like `MyBlogsList`) since its not a page rather a component.

2023-05-12 06:06 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +        <div className="blog_tags flex flex-row items-center mb-4">
Lets avoid using snake_case in our class namings.

2023-05-12 06:06 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +              className="blog_tag mr-2 px-2 py-1 bg-gray-100 text-gray-500 rounded-full text-xs"
Lets avoid using snake_case in our class namings here as well.

2023-05-12 06:06 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +        <p className="blog_description mt-3 mb-3 text-sm font-thin text-gray-500 break-words overflow-hidden line-clamp-3 leading-snug">
Here too.

2023-05-12 06:07 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +            <span className="blog_writter_name m-0   text-gray-600 leading-5">
[very-nit] can you remove the unnecessary space after m-0?

2023-05-12 06:35 UTC, ruthgdb commented on Web/starter_project_iconics/components/blog/BlogCard.tsx
> +  if (status == undefined) status = 'pending'
it can be destructed in such a way,

`= ({ blog: { author, description, datePosted, title, tags, imgUrl, likes, status }, isMyBlogsPage }) => {`

2023-05-12 12:02 UTC, ruthgdb requested changes
Make sure you address this comments before re-requesting :)

2023-05-12 12:02 UTC, ruthgdb commented on Web/starter_project_iconics/pages/profile/index.tsx
> +      <div className="flex   py-4">
[very-nit] remove the space after flex

2023-05-12 12:02 UTC, ruthgdb commented on Web/starter_project_iconics/pages/profile/index.tsx
> +          className={`text-lg font-semibold  text-tertiary px-4 pt-2 pb-5 hover:text-primary ${
[very-nit] remove the space after font-semibold

2023-05-15 13:02 UTC, ruthgdb requested changes
Ive left some comments for you to address

2023-05-16 07:29 UTC, blenassefa2 commented on Web/starter_project_iconics/components/blog/BlogCardFooter.tsx
> +  numberOfLikes: number
but we need the card info we will display in the footer

2023-05-16 12:58 UTC, ruthgdb submitted a review, later dismissed
Good job.

2023-05-17 07:45 UTC, ruthgdb approved these changes

2023-05-17 07:46 UTC, merged