Bereket.mobilefoldersetup
RealEskalate/Internship-2023 pull request #6
Opened 2023-04-12 17:20 UTC by BekyH

2023-04-13 06:53 UTC, Redi22 approved these changes

2023-04-13 06:53 UTC, Redi22 commented on Mobile/dark_knights/lib/features/example/domain/repositories/exaample_repo..dart
Can we rename this to example_repository?

2023-04-13 06:53 UTC, Redi22 commented on Mobile/dartsmiths/lib/features/example/domain/repositories/exaample_repo..dart
rename to example_repository

2023-04-13 06:53 UTC, Redi22 commented on Mobile/matador/lib/features/example/domain/repositories/exaample_repo..dart
rename to example_repository

2023-04-13 06:53 UTC, Redi22 commented on Mobile/matador/lib/features/example/data/repositories/example_repo_impl.dart
rename to example_repository_impl. Same applies for the other 2 similar files in the other projects

2023-04-13 07:36 UTC, YiseBoge requested changes
I would approve this but for the sake of consistency i would aks the project names be renamed in the format of "starter_project_[team name]"

2023-04-13 13:45 UTC, YiseBoge submitted a review, later dismissed

2023-04-13 16:29 UTC, lealemgetahun submitted a review, later dismissed

2023-04-13 17:19 UTC, lealemgetahun approved these changes

2023-04-14 07:43 UTC, YiseBoge approved these changes

2023-04-14 07:50 UTC, merged