feat(mobile - dart knight): implement the homepage
RealEskalate/Internship-2023 pull request #60
Opened 2023-04-25 09:08 UTC by SimonMekonnen

Title: Add homepage

Description:
this pull request is to add the homepage to the project. the homepage is a simple page that shows different articles.

Changes Made:
      - create the filter buttons for the homepage
      - create the profile picture as a widget
      - create a card for holding the article info and image 
      - create the search bar for the homepage
      - customize fonts
      - layout all the components 
Screenshots:
![photo_2023-04-25_00-37-27](https://user-images.githubusercontent.com/96548471/234229395-8abf8ca0-3684-40be-9f4c-edf98265e2f5.jpg)

2023-04-25 12:03 UTC, lealemgetahun requested changes

2023-04-25 12:03 UTC, lealemgetahun commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/articleImage_widget.dart
> +                      color: Color(0xFF424242),
Avoid using fixed colors. Have a separate file in /core/utils and define the colors there.

2023-04-25 12:03 UTC, lealemgetahun commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/articleImage_widget.dart
use small_snack_case for file name. Rename it to articel_image_widget

2023-04-25 12:03 UTC, lealemgetahun commented on Mobile/starter_project_dark_knights/assets/images/do.jpg
use descriptive names for the images

2023-04-27 12:50 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/screen/home_page.dart
> +          // const ArticleCard()
Done!

2023-04-27 12:51 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/filters_widget.dart
> +              color: active == false ? const Color(0xFF376AED) : Colors.white)),
Done!

2023-04-27 12:51 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/articlecard_widget.dart
Done!

2023-04-27 12:51 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/articleInfo_widget.dart
Done!

2023-04-27 12:52 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/widgets/articleImage_widget.dart
Done!

2023-04-27 12:52 UTC, SimonMekonnen commented on Mobile/starter_project_dark_knights/assets/images/do.jpg
Done!

2023-04-28 12:07 UTC, Redi22 requested changes

2023-04-28 12:07 UTC, Redi22 commented on Mobile/starter_project_dark_knights/lib/features/feeds/presentation/screen/home_page.dart
> +                  Filters(
let us use builders for this.

2023-05-02 07:54 UTC, Redi22 approved these changes
LGTM

2023-05-02 11:10 UTC, lealemgetahun approved these changes

2023-05-03 08:04 UTC, Redi22 approved these changes
LGTM

2023-05-03 08:04 UTC, merged