Implement log in screen
RealEskalate/Internship-2023 pull request #63
Opened 2023-04-25 12:11 UTC by Feruz2

![Screenshot (364)](https://user-images.githubusercontent.com/86770648/234271604-17d7fc10-0700-4655-b4db-1cb8d5535988.png)

Description: This is a login page 

Chages made: Added assests folder

2023-04-25 12:18 UTC, Redi22 commented
Is adding assets folder the only change made? Make sure to indicate all the changes or describe the changes as a whole

2023-04-25 12:39 UTC, BekyH requested changes

2023-04-25 12:39 UTC, BekyH commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +              //width: 200, // set the width of the image
remove unnecessary comments.

2023-04-25 12:39 UTC, BekyH commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +                  height: 50,
Avoid giving fixed sizes. Make use of MediaQuery.

2023-04-25 12:39 UTC, BekyH commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +                  color: Colors.blue[900],
Avoid giving colors like this. Define All colors inside the core/utils directory and make use of them whenever needed.

2023-04-25 12:39 UTC, BekyH commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +                        style: TextStyle(
Avoid giving styles like this. Define All styles inside the core/utils directory and make use of them whenever needed.

2023-04-25 12:39 UTC, BekyH commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +                      child: TextField(
There is a button on this text field in the design. Check the design again.

2023-04-25 13:04 UTC, lealemgetahun requested changes
Modularise your code.

2023-04-28 12:22 UTC, Redi22 requested changes

2023-04-28 12:22 UTC, Redi22 commented on Mobile/starter_project_dark_knights/lib/core/utils/text_style.dart
remove all duplicate styles from this file and rename the variables. instead of username your should try formFieldTextStyle

2023-04-28 12:22 UTC, Redi22 commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
> +class Login extends StatelessWidget {
rename to LoginPage

2023-04-28 12:22 UTC, Redi22 commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/screen/log_in_screen.dart
convention is to use login_page.dart

2023-04-28 12:22 UTC, Redi22 commented on Mobile/starter_project_dark_knights/lib/features/Authentication/presentation/widgets/navigation_bar.dart
> +class Navigation extends StatelessWidget {
the name is a bit confusing tbh can we rename it to be specific

2023-05-02 16:49 UTC, BekyH approved these changes

2023-05-03 08:07 UTC, lealemgetahun approved these changes

2023-05-03 08:29 UTC, Redi22 approved these changes
LGTM

2023-05-03 08:33 UTC, merged