Segni.mobile responsive nav
RealEskalate/Internship-2023 pull request #72
Opened 2023-04-26 05:30 UTC by Segnicho

![Screenshot 2023-04-26 8 28 59 AM](https://user-images.githubusercontent.com/88204792/234478109-8c9f757b-6996-455a-9373-782247bf1abc.png)
added z-index and made mobile responsive

2023-04-26 12:20 UTC, Adona12 commented on Web/starter_project_vanguard/public/img/profilePhoto.png
Let's use kabab case for everything other than components

2023-04-26 12:21 UTC, Adona12 commented on Web/starter_project_vanguard/pages/profile/index.tsx
> +      <div className="pt-6 text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700">
The text color can be defined globally for others to use

2023-04-26 12:22 UTC, Adona12 commented on Web/starter_project_vanguard/components/profile/user.ts
Let's move this file in to `/data` subfolder

2023-04-26 12:24 UTC, Adona12 commented on Web/starter_project_vanguard/components/layout/navbar.tsx
> +          <button className="bg-primary text-white rounded-md w-[78px] h-[36px] md:float-right">
Let's use the globally define button styles

2023-04-27 05:11 UTC, Segnicho commented
![Screenshot 2023-04-27 8 10 37 AM](https://user-images.githubusercontent.com/88204792/234765073-d0766f7d-f4a6-43a0-8119-cef26255b551.png)

2023-04-27 12:48 UTC, jebessaD commented
> ![Screenshot 2023-04-27 8 10 37 AM](https://user-images.githubusercontent.com/88204792/234765073-d0766f7d-f4a6-43a0-8119-cef26255b551.png)

The font you used has serifs. There are no serifs on the provided UI.
Please confirm that you used the same font.

2023-04-27 13:11 UTC, jebessaD requested changes

2023-04-27 13:11 UTC, jebessaD commented on Web/starter_project_vanguard/components/layout/Navbar.tsx
> +    <div className="sticky top-0 z-50 bg-white bg-opacity-100 flex justify-between font-montserrat px-10 pt-5">
[check here](https://fonts.google.com/specimen/Montserrat)
As you can see from the above link, the Montserrat font does not have serifs; I'm not sure why the font you used did. Please validate that the font you used and the UI's visual appearance are the same.

2023-04-27 13:11 UTC, jebessaD commented on Web/starter_project_vanguard/components/layout/Navbar.tsx
> +          {' '}
Remove unnecessary code  `{' '}`

2023-04-27 13:11 UTC, jebessaD commented on Web/starter_project_vanguard/components/layout/Navbar.tsx
> +  const [active, setActive] = useState("/")
It is better if you can add the type.
`const [active, setActive] = useState<string>("/")` like this

2023-04-28 07:56 UTC, ruthgdb requested changes

2023-04-28 07:56 UTC, ruthgdb commented on Web/starter_project_vanguard/components/layout/data/nav-items.ts
You should move this file to data/layout folder.

2023-04-28 11:59 UTC, Segnicho commented on Web/starter_project_vanguard/components/layout/data/nav-items.ts
Ok, i did

2023-05-02 07:43 UTC, sam5235 approved these changes

2023-05-02 17:04 UTC, ruthgdb approved these changes
LGTM. Well done.

2023-05-03 06:38 UTC, jebessaD approved these changes
LG

2023-05-03 06:39 UTC, merged