feat(Web-vanguard): implement add New Blog
RealEskalate/Internship-2023 pull request #93
Opened 2023-04-27 11:34 UTC by zelalemyetsedaw

In this branch i implement the add-new-blog pages 
to do this i create two components in @components/ blog folder.

The output is
![localhost_3000_blog_add-new-blog](https://user-images.githubusercontent.com/96313277/234849989-1e22dfd2-c6b1-4bdd-86b1-ef1c6b80f81c.png)

2023-05-02 08:25 UTC, sam5235 commented on Web/starter_project_vanguard/pages/blog/add-new-blog.tsx
> +  const tags = [
make this tags outside of the code in data folder then import it here. because there might be change on the tags ever time.

2023-05-02 08:57 UTC, Segnicho commented on Web/starter_project_vanguard/components/blog/FileUpload.tsx
> +      <Image src='/images/illustration.jpg' alt="illustration image" width={200} height={200}/>
i think it is better if all imports aren't written inline here. import the above the component.

2023-05-02 08:58 UTC, Segnicho commented on Web/starter_project_vanguard/components/blog/TextEditor.tsx
> +const QuillToolbarOptions = [
this data should also be in the data folder.

2023-05-02 09:01 UTC, Segnicho commented on Web/starter_project_vanguard/components/blog/TextEditor.tsx
> +const QuillToolbarOptions = [
since it isn't coming from the backend it is ok to leave it here, i guess.

2023-05-04 12:47 UTC, ruthgdb requested changes
Looks nice overall. Ive left some comments for you to address before we can merge this.

2023-05-04 12:47 UTC, ruthgdb commented on Web/starter_project_vanguard/public/images/illustration.JPG
Can you put this file under /blogs folder to keep it organized

2023-05-04 12:47 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/blog/add-new-blog.tsx
> +  const handleClick = (t: string): void => setActive(t)
Whats t? Can you give it a more descriptive name

2023-05-04 12:47 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/blog/add-new-blog.tsx
> +              className="block w-full  px-4 text-2xl md:text-3xl    border-l-2 outline-none border-blue-700 font-montserrat  "
Use the predefinned colors in your theme here

2023-05-04 12:47 UTC, ruthgdb commented on Web/starter_project_vanguard/pages/blog/add-new-blog.tsx
If you add a page folder (in this case 'blog') under pages folder, it should contain and index.tsx file since thats the file it looks to render when you go to /blog route.

Look at [this](https://nextjs.org/docs/routing/introduction) doc for more info.

2023-05-19 14:55 UTC, closed without merging

2023-05-19 14:55 UTC, zelalemyetsedaw commented
i already done it on another branch